// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package examples

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/invopop/popui.go"
	"github.com/invopop/popui.go/props"
)

// A tree does not have to come from a schema. Value overrides what selecting
// a field emits, so the path a user reads can differ from the string the
// consumer needs — here, Go template variables.
var emailVariables = []props.Field{
	{Name: "job_id", Path: "job_id", Value: "{{.job_id}}", Title: "Job ID", Type: "string", AlwaysPresent: true},
	{Name: "faults", Path: "faults", Value: "{{.faults}}", Title: "Faults", Type: "string"},
	{Name: "doc", Path: "doc", Title: "Document", Type: "object", AlwaysPresent: true, Children: []props.Field{
		{Name: "code", Path: "doc.code", Value: "{{.doc.code}}", Title: "Code", Type: "string"},
		{Name: "supplier", Path: "doc.supplier", Title: "Supplier", Type: "object", AlwaysPresent: true, Children: []props.Field{
			{Name: "name", Path: "doc.supplier.name", Value: "{{.doc.supplier.name}}", Title: "Name", Type: "string"},
		}},
	}},
}

func FieldSelectorCustomFieldsExample() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = popui.FieldSelector(props.FieldSelector{
			Name:        "variable",
			Root:        "email",
			Placeholder: "Insert a variable",
			Fields:      emailVariables,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
