// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package examples

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/invopop/popui.go"
	"github.com/invopop/popui.go/props"
)

func Colors() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = popui.Header(props.Header{
				Breadcrumbs: []props.Breadcrumb{
					{Label: "Colors"},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
						templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
						if !templ_7745c5c3_IsBuffer {
							defer func() {
								templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err == nil {
									templ_7745c5c3_Err = templ_7745c5c3_BufErr
								}
							}()
						}
						ctx = templ.InitializeContext(ctx)
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "Color Catalogue")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
						return nil
					})
					templ_7745c5c3_Err = popui.Title().Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <p class=\"text-foreground-default-secondary mb-8\">Application-specific color tokens from the PopUI design system.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = colorSectionTokens().Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = popui.Article().Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = popui.Main(props.Main{Center: true}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = popui.App(props.App{Title: "Invopop - Color Catalogue"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ---------------------------------------------------------------------------
// Token Colors (Application-Specific)
// ---------------------------------------------------------------------------
func colorSectionTokens() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<section class=\"mb-12\"><h2 class=\"text-xl font-semibold mb-1 tracking-tighter\">Token Colors</h2><p class=\"text-sm text-foreground-default-secondary mb-6\">Application-specific tokens for foreground, background, border, and icon.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Foreground", []colorTokenDef{
			{"foreground-default-default", "neutral-100"},
			{"foreground-default-secondary", "neutral-50"},
			{"foreground-default-tertiary", "neutral-40"},
			{"foreground-inverse-default", "white"},
			{"foreground-inverse-secondary", "neutral-white-alpha-70"},
			{"foreground-accent-default", "accent-60"},
			{"foreground-accent-default-hover", "accent-70"},
			{"foreground-selected-default", "accent-60"},
			{"foreground-selected-default-hover", "accent-70"},
			{"foreground-success-default", "positive-60"},
			{"foreground-info-default", "info-50"},
			{"foreground-attention-default", "attention-60"},
			{"foreground-warning-default", "warning-60"},
			{"foreground-critical-default", "critical-50"},
			{"foreground-document-pdf", "documents-pdf-50"},
			{"foreground-document-xml", "documents-xml-50"},
			{"foreground-document-png", "documents-img-50"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Foreground Status", []colorTokenDef{
			{"foreground-status-invalid", "critical-50"},
			{"foreground-status-empty", "neutral-alpha-50"},
			{"foreground-status-draft", "warning-60"},
			{"foreground-status-processing", "attention-60"},
			{"foreground-status-registered", "personalization-60"},
			{"foreground-status-sent", "info-60"},
			{"foreground-status-received", "personalization-sky-60"},
			{"foreground-status-paid", "positive-60"},
			{"foreground-status-completed", "personalization-aqua-60"},
			{"foreground-status-error", "critical-50"},
			{"foreground-status-rejected", "personalization-magenta-60"},
			{"foreground-status-void", "neutral-alpha-50"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Background", []colorTokenDef{
			{"background-default-default", "neutral-white-alpha-100"},
			{"background-default-secondary", "neutral-alpha-5"},
			{"background-default-tertiary", "neutral-alpha-10"},
			{"background-default-tertiary-hover", "neutral-alpha-20"},
			{"background-default-tertiary-press", "neutral-alpha-30"},
			{"background-default-bold", "accent-80"},
			{"background-default-accent", "brand-50"},
			{"background-default-negative", "neutral-100"},
			{"background-selected-default", "accent-alpha-10"},
			{"background-selected-default-hover", "accent-alpha-20"},
			{"background-selected-default-press", "accent-alpha-30"},
			{"background-selected-inverse", "neutral-white-alpha-10"},
			{"background-selected-inverse-hover", "neutral-white-alpha-20"},
			{"background-selected-inverse-press", "neutral-white-alpha-30"},
			{"background-accent-default", "accent-50"},
			{"background-accent-default-hover", "accent-60"},
			{"background-accent-default-press", "accent-70"},
			{"background-info-default", "info-alpha-10"},
			{"background-info-bold", "info-60"},
			{"background-success-default", "positive-alpha-10"},
			{"background-success-bold", "positive-50"},
			{"background-attention-default", "attention-alpha-10"},
			{"background-warning-default", "warning-alpha-10"},
			{"background-warning-bold", "warning-60"},
			{"background-warning-inverse", "warning-50"},
			{"background-critical-default", "critical-alpha-10"},
			{"background-critical-bold", "critical-50"},
			{"background-critical-inverse", "critical-40"},
			{"background-document-pdf", "documents-pdf-alpha-5"},
			{"background-document-xml", "documents-xml-alpha-5"},
			{"background-document-png", "documents-img-alpha-5"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Background Status", []colorTokenDef{
			{"background-status-invalid", "critical-alpha-10"},
			{"background-status-empty", "neutral-white-alpha-100"},
			{"background-status-draft", "warning-alpha-10"},
			{"background-status-processing", "attention-alpha-10"},
			{"background-status-registered", "personalization-alpha-10"},
			{"background-status-sent", "info-alpha-10"},
			{"background-status-received", "personalization-sky-alpha-10"},
			{"background-status-paid", "positive-alpha-10"},
			{"background-status-completed", "personalization-aqua-alpha-10"},
			{"background-status-error", "critical-alpha-10"},
			{"background-status-rejected", "personalization-magenta-alpha-10"},
			{"background-status-void", "neutral-alpha-10"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Border", []colorTokenDef{
			{"border-default-default", "neutral-alpha-10"},
			{"border-default-secondary", "neutral-alpha-20"},
			{"border-default-secondary-hover", "neutral-alpha-30"},
			{"border-default-tertiary", "neutral-alpha-40"},
			{"border-inverse-default", "neutral-white-alpha-10"},
			{"border-inverse-secondary", "neutral-white-alpha-20"},
			{"border-selected-default", "accent-alpha-10"},
			{"border-selected-bold", "accent-50"},
			{"border-critical-bold", "critical-50"},
			{"border-warning-default", "warning-alpha-10"},
			{"border-warning-bold", "warning-50"},
			{"border-document-pdf", "documents-pdf-alpha-10"},
			{"border-document-xml", "documents-xml-alpha-10"},
			{"border-document-png", "documents-img-alpha-10"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Icon", []colorTokenDef{
			{"icon-default-default", "neutral-alpha-50"},
			{"icon-default-secondary", "neutral-alpha-30"},
			{"icon-default-bold", "neutral-100"},
			{"icon-inverse-default", "neutral-white-alpha-70"},
			{"icon-inverse-secondary", "neutral-white-alpha-40"},
			{"icon-inverse-bold", "neutral-white-alpha-100"},
			{"icon-selected-default", "positive-50"},
			{"icon-accent-default", "accent-50"},
			{"icon-success-default", "positive-50"},
			{"icon-info-default", "info-50"},
			{"icon-attention-default", "attention-50"},
			{"icon-warning-default", "warning-50"},
			{"icon-warning-inverse", "warning-50"},
			{"icon-critical-default", "critical-50"},
			{"icon-critical-inverse", "critical-40"},
			{"icon-document-pdf", "documents-pdf-50"},
			{"icon-document-xml", "documents-xml-50"},
			{"icon-document-png", "documents-img-50"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = colorTokenGroup("Icon Status", []colorTokenDef{
			{"icon-status-invalid", "critical-40"},
			{"icon-status-empty", "neutral-20"},
			{"icon-status-draft", "warning-50"},
			{"icon-status-processing", "attention-50"},
			{"icon-status-registered", "personalization-50"},
			{"icon-status-sent", "info-50"},
			{"icon-status-received", "personalization-sky-50"},
			{"icon-status-paid", "positive-50"},
			{"icon-status-completed", "personalization-aqua-50"},
			{"icon-status-error", "critical-40"},
			{"icon-status-rejected", "personalization-magenta-50"},
			{"icon-status-void", "neutral-50"},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// ---------------------------------------------------------------------------
// Helper types and components
// ---------------------------------------------------------------------------

type colorTokenDef struct {
	name string
	ref  string
}

func colorTokenGroup(title string, tokens []colorTokenDef) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"mb-8\"><h3 class=\"text-lg font-medium mb-3 tracking-tight\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/colors.templ`, Line: 181, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</h3><div class=\"border border-border-default-default rounded-lg overflow-hidden divide-y divide-border-default-default\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, t := range tokens {
			templ_7745c5c3_Err = colorTokenRow(t).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func colorTokenRow(t colorTokenDef) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"flex items-center gap-3 px-3 py-2\"><div class=\"h-8 w-8 rounded-md border border-border-default-default shrink-0 relative overflow-hidden\"><div class=\"absolute inset-0\" style=\"background-image: repeating-conic-gradient(#e5e5e5 0% 25%, transparent 0% 50%); background-size: 8px 8px;\"></div><div class=\"absolute inset-0\" style=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(templ.SafeCSS("background-color: var(--color-" + t.name + ")"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/colors.templ`, Line: 201, Col: 74}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"></div></div><div class=\"flex flex-col min-w-0\"><span class=\"text-sm font-medium text-foreground-default-default truncate\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var11 string
		templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(t.name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/colors.templ`, Line: 205, Col: 86}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</span> <span class=\"text-xs text-foreground-default-secondary font-mono truncate\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(t.ref)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `examples/colors.templ`, Line: 206, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
